# Generated by Django 5.2.8 on 2025-11-26 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shuttlerequest',
            options={'ordering': ['start_time'], 'verbose_name': 'คำขอใช้รถ', 'verbose_name_plural': 'คำขอใช้รถทั้งหมด'},
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='สีรถ'),
        ),
        migrations.AddField(
            model_name='shuttlerequest',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='ส่งการแจ้งเตือนแล้ว'),
        ),
        migrations.AddField(
            model_name='shuttlerequest',
            name='queue_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขคิว'),
        ),
        migrations.AddField(
            model_name='shuttlerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='ทะเบียนรถ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ชื่อรถ'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.car', verbose_name='รถ'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.driver', verbose_name='คนขับ'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='dropoff_location',
            field=models.CharField(max_length=200, verbose_name='จุดส่ง'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='LINE ID'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='pickup_location',
            field=models.CharField(max_length=200, verbose_name='จุดรับ'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='start_time',
            field=models.DateTimeField(verbose_name='เวลาเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'อนุมัติ'), ('on_the_way', 'กำลังถึงต้นทาง'), ('in_progress', 'กำลังเดินทาง'), ('done', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='shuttlerequest',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อผู้ใช้'),
        ),
    ]
